### PR TITLE
Eglot support

### LINKED ISSUE #21: Add support for Eglot (and maybe Eshell)
Thank you for creating this package! It is great and works with most Python packages I use.  However I encountered some problems while extending `pet`'s support to Eglot and Eshell.  I want to discuss them here (I have already made some efforts).

## My workflow

I appreciate that `pet` works with so many virtual environment managers.  Currently I only use Python's built-in `venv`, and have a `.venv` directory in all of my Python projects.  I want packages like `python-pytest` and `flycheck` automatically pick executables and packages from the `.venv` directory, which is handled pretty well by `pet`.

## Problem 1: Eglot integration

[Eglot](https://github.com/joaotavora/eglot) is a light-weight implementation of LSP (language server protocol) inside Emacs, and is built-in since Emacs 29.  I use Eglot to communicate with an external language server (`pylsp` in my case), and the language server can do all sort of things for me, like providing completion via `rope`, formatting my buffer via `black`, linting my buffer via `mypy` and `ruff`, etc..

By default, `eglot` just find the `pylsp` executable via `executable-find`, and launch it as the language server.  However, this by default launches the global `pylsp` executable, instead of the local one inside the virtual environment.  Thus, the global language server cannot recognize the local packages inside the virtual environment (because they are not installed globally), and cannot do its works like linting and providing completions properly.

Can `pet` solve this?  definitely!  I solved the problem with the following steps:

1. Add `eglot-ensure` to `python-mode-hook` (or `python-ts-mode-hook` if tree-sitter is enabled) with a depth of 100, so that `eglot` is always enabled after `pet`.
2. Advice the `eglot--executable-find` function with the `pet` counterpart, like [this](https://github.com/zyxir/emacs.d/blob/0316aaffe0a1814e2247facc94f369049b69b369/init.el#L3155-L3170).

Now Eglot can use the local `pylsp` as expected, only with one drawback: it does not work on TRAMP, because `pet-executable-find` does not work on TRAMP.  Luckily, #20 solves this.  Hope it be merged soon.

My problem is: should my workaround be `pet`'s default behavior?  Since Eglot is very popular (maybe more popular than those other packages that `pet` supports, as it is built-in now), adding its support may not be a bad idea.  If you think so, I can create a PR on this.

## Problem 2: Eshell or Shell integration

When working on my Python projects, sometimes I have to interact with a shell, for example when I have to create the virtual environemnt with `python -m venv .venv`, or when I have to install new packages into the virtual environment with `pip install`, or even when I try to test my package's CLI with `python -m my_awesome_module`.  I don't know if this is only my own unique demand, but I need a shell quite a lot.

First I try to use the `eshell`, but `eshell` cannot activate a virtual environment via `activate .venv/bin/activate`, as `eshell` does not execute Bash commands.

After that, I tried `shell`.  In `shell`, I can activate the virtual environment manually.  But, oh god, why do I have to do things manually as an Emacser?  So I wrote [these code](https://github.com/zyxir/emacs.d/blob/0316aaffe0a1814e2247facc94f369049b69b369/init.el#L3077-L3134) to auto-activate the Python virtual environments, if there is one in the `default-directory` (It is also worth noting that VS Code does this by default).

It seems fine, but:

1. My workaround is my own magical hack.  I didn't use `pet` (which I did want to, but I didn't know how, because I'm not sure if every virtual environment manager offer an "activate" script).
2. My workaround is ugly.  I love `eshell`, it is very Lispy, and provides consistent behavior on every platform I use.  I shoudn't be forced to use `shell` on such basic need, and `shell` even cannot work properly with PowerShell on Windows.  There must be some other workaround for `eshell`.

The final solution to this must be integrating `pet` into `eshell`.  [virtualenvwrapper](https://github.com/porterjamesj/virtualenvwrapper.el) is already able to make `shell`, `eshell` and any other subprocesses aware of the Python virtual environment, despite it support less virtual environment managers than `pet`.

I do want to make `pet` perfect (so that you don't have to install a crazy amount of virtual environment packages), so I expect an opportunity to thouroughly discuss these problems.  If a preferred method is found, I would be more than willing to implement it and create a pull request.

### PR DESCRIPTION
**Pull request by wyuenho**
@zyxir @egelja please delete your custom pet/eglot config in your init file and give this PR a spin, let me know if you've run into any problems.

Closes #21

### CODE REVIEW

**Comment by zyxir** [comment]
I am using this branch now. No issue observed. Will report if any problem occurs.

**Comment by tusharhero** [comment]
How long until this is merged? Also, will it support `vterm` shell too? (activating the virtual environment every time the `vterm` is launched there)

**Comment by tusharhero** [comment]
How can I try this pr?

**Comment by wyuenho** [comment]
@tusharhero as stated many times elsewhere, and even on the issue this PR references, PET is not a virtualenv manager/wrapper/activation script etc. How you activate the virtualenv in vterm is how you activate the virtualenv in your terminal, just configure your shell.

**Pull request merged**
